import type { Metadata } from 'next'
import './globals.css'
import { montserratFont } from '@/config/fonts'

export const metadata: Metadata = {
  title: 'Star | Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserratFont.className}>{children}</body>
    </html>
  )
}
